export const CONTACTS = {
  phoneDisplay: "+998 71 205 85 88",
  phoneHref: "tel:+998712058588",
  email: "info@btechnics.uz",
  emailHref: "mailto:info@btechnics.uz",
  telegram: "https://q.me-qr.com/w1e3a4fd",
  website: "https://btechnics.uz",
} as const;

export type LocaleCode = "ru" | "uz";
export type AudienceId = "owner" | "management" | "developer" | "technical";
export type ScenarioId = "energy" | "climate" | "leak" | "access" | "fire";

export const siteCopy = {
  ru: {
    brand: "Buyursin Technics",
    nav: {
      solutions: "Решения",
      scenarios: "Сценарии",
      calculator: "Расчёт",
      projects: "Проекты",
      company: "Компания",
      contacts: "Контакты",
      consultation: "Получить консультацию",
      menu: "Меню",
    },
    hero: {
      badge: "BMS и автоматизация зданий",
      titleA: "Управляйте зданием.",
      titleB: "Снижайте потери.",
      text: "Объединяем инженерные системы в единый центр управления — для контроля, безопасности и эффективной эксплуатации объектов любого масштаба.",
      primary: "Рассчитать эффективность",
      secondary: "Смотреть решения",
      metrics: [
        { value: "до 30%", label: "потенциал снижения энергозатрат" },
        { value: "24/7", label: "контроль инженерных систем" },
        { value: "1–3 года", label: "ориентир окупаемости" },
        { value: "15 лет", label: "опыт компании" },
      ],
    },
    audience: {
      eyebrow: "Для кого",
      title: "Одна система. Разная ценность для каждой роли.",
      subtitle: "Выберите свою роль — сайт покажет релевантные задачи, выгоды и аргументы.",
      labels: {
        owner: "Владелец",
        management: "Управляющая компания",
        developer: "Девелопер",
        technical: "Технический директор",
      },
      items: {
        owner: {
          headline: "Контролируйте стоимость эксплуатации и защищайте актив.",
          points: ["Прозрачные расходы", "Снижение рисков", "Данные для инвестиционных решений"],
          cta: "Рассчитать экономику объекта",
        },
        management: {
          headline: "Управляйте объектом без разрозненных пультов и таблиц.",
          points: ["Единый диспетчерский экран", "Контроль подрядчиков", "История событий и заявок"],
          cta: "Показать сценарии эксплуатации",
        },
        developer: {
          headline: "Заложите управляемость здания ещё на этапе проекта.",
          points: ["Проектирование и интеграция", "Комплектация и пусконаладка", "Подготовка к передаче в эксплуатацию"],
          cta: "Обсудить проект",
        },
        technical: {
          headline: "Получите понятную архитектуру, совместимость и сервис.",
          points: ["BMS, АСКУЭ, ОВиК и безопасность", "Интеграция оборудования", "Сервис 24/7"],
          cta: "Посмотреть технические решения",
        },
      },
    },
    scenario: {
      eyebrow: "Сценарии",
      title: "Понятно показываем, что происходит и зачем это бизнесу.",
      subtitle: "Без декоративной анимации: проблема, схема работы, интерфейс управления и ожидаемый эффект.",
      tabs: {
        energy: "Энергия",
        climate: "Климат",
        leak: "Протечка",
        access: "Доступ",
        fire: "Пожар",
      },
      labels: {
        problem: "Проблема",
        workflow: "Как работает",
        ownerValue: "Что получает владелец",
        dashboard: "Что видно в панели",
        result: "Результат",
        action: "Рассчитать для моего объекта",
        status: "Статус",
        normal: "В норме",
        alert: "Требует внимания",
      },
      items: {
        energy: {
          problem: "Оборудование работает по фиксированным режимам, а перерасход становится заметен только после получения счёта.",
          steps: ["Счётчики и контроллеры собирают данные", "BMS сравнивает режимы и нагрузку", "Лишние нагрузки отключаются или переносятся"],
          benefits: ["Контроль потребления по зонам", "Прогнозируемый бюджет", "Данные для работы с арендаторами"],
          dashboard: ["Потребление сегодня", "Отклонения от базовой линии", "Пиковые нагрузки", "Экономия по сценариям"],
          result: "Потенциал снижения энергозатрат — до 30% после обследования и настройки сценариев.",
        },
        climate: {
          problem: "Вентиляция и кондиционирование работают без учёта загрузки помещений, температуры и качества воздуха.",
          steps: ["Датчики измеряют температуру, влажность и CO₂", "Система оценивает присутствие и режим зоны", "ОВиК автоматически меняет производительность"],
          benefits: ["Комфорт арендаторов", "Меньше жалоб", "Снижение нагрузки на оборудование"],
          dashboard: ["Температура по зонам", "CO₂ и влажность", "Активные режимы", "Отклонения и рекомендации"],
          result: "Комфорт поддерживается автоматически, а оборудование работает только там и тогда, где это нужно.",
        },
        leak: {
          problem: "Незаметная протечка может повредить отделку, оборудование и товарные запасы, а также остановить работу объекта.",
          steps: ["Датчик фиксирует воду", "Система определяет зону и уведомляет ответственных", "При наличии автоматики перекрывается вода и создаётся событие"],
          benefits: ["Раннее обнаружение", "Меньше затрат на восстановление", "Защита имущества и оборудования"],
          dashboard: ["Место события", "Время и датчик", "Статус реакции", "Рекомендованное действие"],
          result: "Проблема фиксируется в момент возникновения, а не после того, как ущерб уже заметен.",
        },
        access: {
          problem: "Разрозненные системы доступа усложняют контроль сотрудников, подрядчиков, гостей и критических зон.",
          steps: ["Система идентифицирует пользователя", "Проверяет права и расписание", "Разрешает или блокирует проход и сохраняет событие"],
          benefits: ["Контроль критических зон", "Учёт посещений", "Единая история доступа"],
          dashboard: ["События прохода", "Заблокированные попытки", "Права пользователей", "Загрузка зон"],
          result: "Доступ управляется из одного интерфейса и связан с общими сценариями безопасности здания.",
        },
        fire: {
          problem: "При аварии важно не только обнаружить событие, но и синхронно запустить оповещение, доступ и инженерные системы.",
          steps: ["Система получает сигнал тревоги", "Проверяет зону и запускает сценарий", "Оповещение, двери, вентиляция и диспетчеризация работают согласованно"],
          benefits: ["Быстрая реакция", "Согласованные действия систем", "Журнал событий для анализа"],
          dashboard: ["Зона тревоги", "Активный сценарий", "Состояние оборудования", "Подтверждение ответственных"],
          result: "Инженерные и слаботочные системы действуют как единый комплекс, а не как отдельные устройства.",
        },
      },
    },
    comparison: {
      eyebrow: "До и после",
      title: "От реактивного управления — к понятной системе принятия решений.",
      beforeTitle: "До внедрения",
      afterTitle: "После внедрения",
      before: ["Данные разрознены", "Проблемы замечают по факту", "Ручные процессы и таблицы", "Расходы трудно объяснить"],
      after: ["Все системы в одном интерфейсе", "Отклонения видны сразу", "Сценарии запускаются автоматически", "Есть история и аналитика"],
    },
    calculator: {
      eyebrow: "Предварительный расчёт",
      title: "Оцените возможный эффект для вашего объекта.",
      subtitle: "Расчёт использует ориентировочные диапазоны. Точные значения определяются после технического аудита.",
      role: "Ваша роль",
      objectType: "Тип объекта",
      area: "Площадь, м²",
      monthlyEnergy: "Расходы на энергию в месяц",
      monthlyOps: "Эксплуатационные расходы в месяц",
      automation: "Текущий уровень автоматизации",
      scenarios: "Приоритетные задачи",
      currency: "Валюта",
      calculate: "Показать расчёт",
      resultTitle: "Предварительный результат",
      annualEffect: "Ориентировочный эффект в год",
      savingRange: "Диапазон экономии",
      payback: "Сценарный срок окупаемости",
      recommended: "Рекомендуемые решения",
      audit: "Заказать точный аудит",
      disclaimer: "Это ориентировочная модель по средним показателям. Она не является коммерческой гарантией.",
      types: ["Бизнес-центр", "Торговый объект", "Отель", "Жилой комплекс", "Склад / производство", "Другое"],
      automationLevels: ["Нет единой автоматизации", "Частичная диспетчеризация", "Есть BMS, требуется модернизация"],
    },
    solutions: {
      eyebrow: "Решения",
      title: "Комплексная автоматизация — от проекта до сервиса 24/7.",
      subtitle: "Можно внедрять систему целиком или поэтапно, начиная с наиболее дорогих потерь и рисков.",
      cards: [
        { id: "bms", title: "BMS", text: "Единое управление инженерными системами, сценариями, тревогами и аналитикой.", points: ["Диспетчеризация", "Сценарии", "Отчёты"] },
        { id: "metering", title: "АСКУЭ", text: "Точный учёт и баланс энергоресурсов по объектам, зонам и арендаторам.", points: ["Почасовой учёт", "Тренды", "Контроль лимитов"] },
        { id: "hvac", title: "ОВиК и климат", text: "Автоматическое управление вентиляцией, отоплением и кондиционированием.", points: ["Температура", "CO₂", "Режимы"] },
        { id: "light", title: "Освещение", text: "Расписания, датчики присутствия и сценарии для зон общего пользования.", points: ["Автоматизация", "Диммирование", "Экономия"] },
        { id: "water", title: "Вода и протечки", text: "Контроль расхода, датчики протечки и автоматические действия.", points: ["Раннее обнаружение", "Перекрытие", "Журнал событий"] },
        { id: "fire", title: "Пожарная безопасность", text: "Интеграция пожарной автоматики, оповещения и инженерных сценариев.", points: ["АПС", "СОУЭ", "Сценарии"] },
        { id: "access", title: "Доступ и видео", text: "СКУД, видеонаблюдение и единый контроль событий безопасности.", points: ["Доступ", "Видео", "Архив"] },
        { id: "service", title: "Сервис 24/7", text: "Поддержка, диагностика, обновления и контроль работоспособности.", points: ["SLA", "Мониторинг", "Поддержка"] },
      ],
      more: "Подробнее",
    },
    process: {
      eyebrow: "Как внедряем",
      title: "Пять понятных этапов без скрытой магии.",
      steps: [
        { title: "Аудит", text: "Изучаем объект, расходы, риски и существующие системы." },
        { title: "Концепция", text: "Формируем архитектуру, сценарии и ожидаемый эффект." },
        { title: "Проект", text: "Разрабатываем документацию, спецификацию и план внедрения." },
        { title: "Монтаж и пуск", text: "Интегрируем оборудование, программируем и тестируем сценарии." },
        { title: "Сервис", text: "Поддерживаем систему, анализируем данные и улучшаем режимы." },
      ],
    },
    projects: {
      eyebrow: "Опыт",
      title: "Объекты и бренды компании.",
      subtitle: "Перед публикацией детальных кейсов подтверждаем цифры, состав работ и право использования материалов.",
      clients: ["Centris Towers", "Sberbank City", "BMW", "Sheraton", "Swissôtel", "IKEA Aviapark", "Ozon Arena", "ЖК I’m"],
      partners: ["Siemens", "Honeywell", "Legrand", "Interra", "ITC"],
      cta: "Обсудить похожий объект",
    },
    company: {
      eyebrow: "О компании",
      title: "Инженерный интегратор полного цикла.",
      text: "Проектирование, поставка, монтаж, программирование, пусконаладка и сервис инженерных и слаботочных систем.",
      facts: [
        { value: "15 лет", label: "опыт компании" },
        { value: "24/7", label: "сервис и мониторинг" },
        { value: "ISO", label: "сертификации" },
        { value: "полный цикл", label: "от проекта до эксплуатации" },
      ],
      certifications: ["ISO 9001:2015", "ISO/IEC 27001:2022", "Siemens Solution Partner", "Партнёрские решения Honeywell и Legrand"],
    },
    contact: {
      eyebrow: "Контакты",
      title: "Расскажите об объекте — начнём с понятного следующего шага.",
      subtitle: "Можно заказать расчёт, технический аудит, консультацию или подготовку коммерческого предложения.",
      phone: "Телефон",
      email: "Email",
      telegram: "Telegram",
      formTitle: "Отправить заявку",
      name: "Имя",
      company: "Компания",
      contactField: "Телефон или Telegram",
      message: "Задача или объект",
      submit: "Отправить",
      sending: "Отправляем…",
      success: "Заявка подготовлена. Мы свяжемся с вами по указанному контакту.",
      fallback: "Откроется почтовое приложение с заполненным письмом.",
    },
    footer: {
      text: "Автоматизация инженерных и слаботочных систем коммерческих зданий.",
      internal: "Сформировать КП",
    },
  },
  uz: {
    brand: "Buyursin Technics",
    nav: {
      solutions: "Yechimlar",
      scenarios: "Ssenariylar",
      calculator: "Hisob-kitob",
      projects: "Loyihalar",
      company: "Kompaniya",
      contacts: "Aloqa",
      consultation: "Maslahat olish",
      menu: "Menyu",
    },
    hero: {
      badge: "BMS va binolarni avtomatlashtirish",
      titleA: "Binoni boshqaring.",
      titleB: "Yo‘qotishlarni kamaytiring.",
      text: "Muhandislik tizimlarini yagona boshqaruv markaziga birlashtiramiz — har qanday miqyosdagi obyektlarni nazorat qilish, xavfsiz va samarali ishlatish uchun.",
      primary: "Samaradorlikni hisoblash",
      secondary: "Yechimlarni ko‘rish",
      metrics: [
        { value: "30% gacha", label: "energiya xarajatlarini kamaytirish salohiyati" },
        { value: "24/7", label: "muhandislik tizimlari nazorati" },
        { value: "1–3 yil", label: "taqdimot ma’lumotlariga ko‘ra qoplanish muddati" },
        { value: "15 yil", label: "kompaniya tajribasi" },
      ],
    },
    audience: {
      eyebrow: "Kim uchun",
      title: "Bitta tizim. Har bir rol uchun aniq foyda.",
      subtitle: "Rolingizni tanlang — sayt sizga mos vazifalar, afzalliklar va dalillarni ko‘rsatadi.",
      labels: {
        owner: "Bino egasi",
        management: "Boshqaruv kompaniyasi",
        developer: "Developer",
        technical: "Texnik direktor",
      },
      items: {
        owner: {
          headline: "Ekspluatatsiya xarajatlarini nazorat qiling va aktivingizni himoya qiling.",
          points: ["Shaffof xarajatlar", "Kamroq xavf", "Investitsiya qarorlari uchun ma’lumot"],
          cta: "Obyekt iqtisodiyotini hisoblash",
        },
        management: {
          headline: "Obyektni alohida pultlar va jadvallarsiz boshqaring.",
          points: ["Yagona dispetcher ekrani", "Pudratchilar nazorati", "Voqealar va arizalar tarixi"],
          cta: "Ekspluatatsiya ssenariylarini ko‘rish",
        },
        developer: {
          headline: "Binoni boshqarish imkoniyatini loyiha bosqichidayoq yarating.",
          points: ["Loyihalash va integratsiya", "Jihozlash va ishga tushirish", "Ekspluatatsiyaga topshirishga tayyorlash"],
          cta: "Loyihani muhokama qilish",
        },
        technical: {
          headline: "Tushunarli arxitektura, moslik va servisga ega bo‘ling.",
          points: ["BMS, ASKUE, HVAC va xavfsizlik", "Uskunalarni integratsiya qilish", "24/7 servis"],
          cta: "Texnik yechimlarni ko‘rish",
        },
      },
    },
    scenario: {
      eyebrow: "Ssenariylar",
      title: "Nima sodir bo‘layotganini va uning biznes uchun foydasini aniq ko‘rsatamiz.",
      subtitle: "Muammo, ish jarayoni, boshqaruv interfeysi va kutiladigan natija — ortiqcha bezaksiz.",
      tabs: { energy: "Energiya", climate: "Iqlim", leak: "Oqish", access: "Kirish", fire: "Yong‘in" },
      labels: {
        problem: "Muammo",
        workflow: "Qanday ishlaydi",
        ownerValue: "Egasi nima oladi",
        dashboard: "Panelda nima ko‘rinadi",
        result: "Natija",
        action: "Obyektim uchun hisoblash",
        status: "Holat",
        normal: "Me’yorda",
        alert: "E’tibor talab qiladi",
      },
      items: {
        energy: {
          problem: "Uskunalar qat’iy rejimda ishlaydi, ortiqcha sarf esa faqat hisob kelgandan keyin bilinadi.",
          steps: ["Hisoblagichlar va kontrollerlar ma’lumot yig‘adi", "BMS rejimlar va yuklamalarni solishtiradi", "Ortiqcha yuklamalar o‘chiriladi yoki boshqa vaqtga ko‘chiriladi"],
          benefits: ["Zonalar bo‘yicha nazorat", "Prognoz qilinadigan budjet", "Ijarachilar bilan ishlash uchun ma’lumot"],
          dashboard: ["Bugungi sarf", "Bazaviy ko‘rsatkichdan og‘ish", "Eng yuqori yuklamalar", "Ssenariylar bo‘yicha tejam"],
          result: "Audit va ssenariy sozlashdan keyin energiya xarajatlarini 30% gacha kamaytirish salohiyati.",
        },
        climate: {
          problem: "Ventilyatsiya va konditsioner tizimlari xonalarning bandligi, harorati va havo sifatini hisobga olmasdan ishlaydi.",
          steps: ["Datchiklar harorat, namlik va CO₂ ni o‘lchaydi", "Tizim zonaning bandligi va ish rejimini baholaydi", "HVAC quvvati avtomatik o‘zgaradi"],
          benefits: ["Ijarachilar uchun qulaylik", "Kamroq shikoyat", "Uskunaga kamroq yuklama"],
          dashboard: ["Zonalar harorati", "CO₂ va namlik", "Faol rejimlar", "Og‘ishlar va tavsiyalar"],
          result: "Komfort avtomatik saqlanadi, uskunalar esa faqat kerakli joy va vaqtda ishlaydi.",
        },
        leak: {
          problem: "Sezilmagan suv oqishi pardoz, uskuna va tovarlarga zarar yetkazib, obyekt ishini to‘xtatishi mumkin.",
          steps: ["Datchik suvni aniqlaydi", "Tizim hodisa zonasini aniqlab, mas’ullarga xabar beradi", "Avtomatika mavjud bo‘lsa, suv yopiladi va voqea jurnalga yoziladi"],
          benefits: ["Erta aniqlash", "Tiklash xarajatlarini kamaytirish", "Mulk va uskunani himoya qilish"],
          dashboard: ["Voqea joyi", "Vaqt va datchik", "Reaksiya holati", "Tavsiya etilgan harakat"],
          result: "Muammo zarar ko‘rinib qolgandan keyin emas, paydo bo‘lgan zahoti qayd etiladi.",
        },
        access: {
          problem: "Tarqoq kirish tizimlari xodimlar, pudratchilar, mehmonlar va muhim zonalarni nazorat qilishni qiyinlashtiradi.",
          steps: ["Tizim foydalanuvchini aniqlaydi", "Kirish huquqi va jadvalni tekshiradi", "Kirishga ruxsat beradi yoki uni bloklaydi va voqeani saqlaydi"],
          benefits: ["Muhim zonalar nazorati", "Tashriflar hisobi", "Yagona kirish tarixi"],
          dashboard: ["Kirish voqealari", "Bloklangan urinishlar", "Foydalanuvchi huquqlari", "Zonalar yuklamasi"],
          result: "Kirish bitta interfeysdan boshqariladi va binoning umumiy xavfsizlik ssenariylariga ulanadi.",
        },
        fire: {
          problem: "Avariya paytida voqeani aniqlash bilan birga ogohlantirish, kirish va muhandislik tizimlarini sinxron ishga tushirish muhim.",
          steps: ["Tizim signalni oladi", "Zona va ssenariyni tekshiradi", "Ogohlantirish, eshiklar, ventilyatsiya va dispetcherlik uyg‘un ishlaydi"],
          benefits: ["Tezkor reaksiya", "Tizimlarning uyg‘un ishlashi", "Tahlil uchun voqealar jurnali"],
          dashboard: ["Xavf zonasi", "Faol ssenariy", "Uskuna holati", "Mas’ullar tasdig‘i"],
          result: "Muhandislik va past tokli tizimlar alohida qurilmalar emas, yagona majmua sifatida ishlaydi.",
        },
      },
    },
    comparison: {
      eyebrow: "Oldin va keyin",
      title: "Reaktiv boshqaruvdan — aniq qarorlar tizimiga.",
      beforeTitle: "Joriy etishdan oldin",
      afterTitle: "Joriy etilgandan keyin",
      before: ["Ma’lumotlar tarqoq", "Muammo sodir bo‘lgach bilinadi", "Qo‘lda bajariladigan jarayonlar", "Xarajat sababini tushuntirish qiyin"],
      after: ["Barcha tizimlar bitta oynada", "Og‘ishlar darhol ko‘rinadi", "Ssenariylar avtomatik ishlaydi", "Tarix va analitika mavjud"],
    },
    calculator: {
      eyebrow: "Dastlabki hisob",
      title: "Obyektingiz uchun mumkin bo‘lgan samarani baholang.",
      subtitle: "Hisob taxminiy diapazonlarga asoslanadi. Aniq qiymatlar texnik auditdan keyin belgilanadi.",
      role: "Sizning rolingiz",
      objectType: "Obyekt turi",
      area: "Maydon, m²",
      monthlyEnergy: "Oylik energiya xarajati",
      monthlyOps: "Oylik ekspluatatsiya xarajati",
      automation: "Hozirgi avtomatlashtirish darajasi",
      scenarios: "Asosiy vazifalar",
      currency: "Valyuta",
      calculate: "Hisobni ko‘rsatish",
      resultTitle: "Dastlabki natija",
      annualEffect: "Yillik taxminiy samara",
      savingRange: "Tejash diapazoni",
      payback: "Hisobiy qoplanish muddati",
      recommended: "Tavsiya etilgan yechimlar",
      audit: "Aniq hisob uchun audit buyurtma qilish",
      disclaimer: "Bu o‘rtacha ko‘rsatkichlarga asoslangan taxminiy model. U tijorat kafolati hisoblanmaydi.",
      types: ["Biznes markazi", "Savdo obyekti", "Mehmonxona", "Turar joy majmuasi", "Ombor / ishlab chiqarish", "Boshqa"],
      automationLevels: ["Yagona avtomatlashtirish yo‘q", "Qisman dispetcherlik", "BMS bor, modernizatsiya kerak"],
    },
    solutions: {
      eyebrow: "Yechimlar",
      title: "Loyihadan 24/7 servisgacha kompleks avtomatlashtirish.",
      subtitle: "Tizimni to‘liq yoki bosqichma-bosqich, eng qimmat yo‘qotish va xavflardan boshlab joriy etish mumkin.",
      cards: [
        { id: "bms", title: "BMS", text: "Muhandislik tizimlari, ssenariylar, ogohlantirish va analitikaning yagona boshqaruvi.", points: ["Dispetcherlik", "Ssenariylar", "Hisobotlar"] },
        { id: "metering", title: "ASKUE", text: "Obyekt, zona va ijarachilar bo‘yicha aniq energiya hisobi va balansi.", points: ["Soatlik hisob", "Trendlar", "Limit nazorati"] },
        { id: "hvac", title: "HVAC va iqlim", text: "Ventilyatsiya, isitish va konditsionerni avtomatik boshqarish.", points: ["Harorat", "CO₂", "Rejimlar"] },
        { id: "light", title: "Yoritish", text: "Jadvallar, mavjudlik datchiklari va umumiy zonalar ssenariylari.", points: ["Avtomatika", "Yorug‘lik darajasini boshqarish", "Tejash"] },
        { id: "water", title: "Suv va oqish", text: "Sarf nazorati, oqish datchiklari va avtomatik harakatlar.", points: ["Erta aniqlash", "Yopish", "Voqealar jurnali"] },
        { id: "fire", title: "Yong‘in xavfsizligi", text: "Yong‘in avtomatikasi, ogohlantirish va muhandislik ssenariylarini integratsiya qilish.", points: ["APS", "SOUE", "Ssenariylar"] },
        { id: "access", title: "Kirish va video", text: "SKUD, videokuzatuv va xavfsizlik voqealarining yagona nazorati.", points: ["Kirish", "Video", "Arxiv"] },
        { id: "service", title: "24/7 servis", text: "Qo‘llab-quvvatlash, diagnostika, yangilash va ishlash nazorati.", points: ["SLA", "Monitoring", "Yordam"] },
      ],
      more: "Batafsil",
    },
    process: {
      eyebrow: "Qanday joriy etamiz",
      title: "Yashirin murakkabliksiz beshta tushunarli bosqich.",
      steps: [
        { title: "Audit", text: "Obyekt, xarajat, xavf va mavjud tizimlarni o‘rganamiz." },
        { title: "Konsepsiya", text: "Arxitektura, ssenariy va kutiladigan samarani shakllantiramiz." },
        { title: "Loyiha", text: "Hujjat, spetsifikatsiya va joriy etish rejasini ishlab chiqamiz." },
        { title: "Montaj va ishga tushirish", text: "Uskunani integratsiya qilib, ssenariylarni sinovdan o‘tkazamiz." },
        { title: "Servis", text: "Tizimni qo‘llab, ma’lumotlarni tahlil qilib, rejimlarni yaxshilaymiz." },
      ],
    },
    projects: {
      eyebrow: "Tajriba",
      title: "Kompaniya taqdimotidagi obyektlar va brendlar.",
      subtitle: "Batafsil keyslarni chiqarishdan oldin raqamlar, ishlar tarkibi va materiallardan foydalanish huquqini tasdiqlaymiz.",
      clients: ["Centris Towers", "Sberbank City", "BMW", "Sheraton", "Swissôtel", "IKEA Aviapark", "Ozon Arena", "ЖК I’m"],
      partners: ["Siemens", "Honeywell", "Legrand", "Interra", "ITC"],
      cta: "O‘xshash obyektni muhokama qilish",
    },
    company: {
      eyebrow: "Kompaniya haqida",
      title: "To‘liq siklli muhandislik integratori.",
      text: "Muhandislik va past tokli tizimlarni loyihalash, yetkazib berish, montaj qilish, dasturlash, ishga tushirish va ularga xizmat ko‘rsatish.",
      facts: [
        { value: "15 yil", label: "taqdimotdagi kompaniya tajribasi" },
        { value: "24/7", label: "servis va monitoring" },
        { value: "ISO", label: "taqdimotda ko‘rsatilgan sertifikatlar" },
        { value: "to‘liq sikl", label: "loyihadan ekspluatatsiyagacha" },
      ],
      certifications: ["ISO 9001:2015", "ISO/IEC 27001:2022", "Siemens Solution Partner", "Honeywell va Legrand hamkorlik yechimlari"],
    },
    contact: {
      eyebrow: "Aloqa",
      title: "Obyekt haqida ayting — tushunarli keyingi qadamdan boshlaymiz.",
      subtitle: "Hisob-kitob, texnik audit, maslahat yoki tijorat taklifini buyurtma qilishingiz mumkin.",
      phone: "Telefon",
      email: "Email",
      telegram: "Telegram",
      formTitle: "Ariza yuborish",
      name: "Ism",
      company: "Kompaniya",
      contactField: "Telefon yoki Telegram",
      message: "Vazifa yoki obyekt",
      submit: "Yuborish",
      sending: "Yuborilmoqda…",
      success: "Ariza tayyorlandi. Ko‘rsatilgan aloqa orqali siz bilan bog‘lanamiz.",
      fallback: "To‘ldirilgan xat bilan pochta ilovasi ochiladi.",
    },
    footer: {
      text: "Tijorat binolarining muhandislik va past tokli tizimlarini avtomatlashtirish.",
      internal: "Tijorat taklifini yaratish",
    },
  },
} as const;

export function copyFor(locale: LocaleCode) {
  return siteCopy[locale];
}
